spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vr-software
    username: postgres
    password: vr-software-interview
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false